# tf.constant

In [2]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [3]:
#creating a scalar 
scalar=tf.constant(2)
scalar

2022-12-01 09:53:28.961439: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-12-01 09:53:28.961474: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2022-12-01 09:53:28.961502: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (mylar-pc): /proc/driver/nvidia/version does not exist


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [5]:
scalar.ndim

0

In [6]:
# creating a vector
vector=tf.constant([2,4])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [7]:
vector.ndim

1

In [8]:
matrix=tf.constant([[2,3],
                   [23,45]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 2,  3],
       [23, 45]], dtype=int32)>

In [9]:
matrix.ndim

2

In [10]:
another_matrix=tf.constant([[20,30],
                           [23,455],
                           [324,55]])
another_matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 20,  30],
       [ 23, 455],
       [324,  55]], dtype=int32)>

In [11]:
another_matrix.ndim

2

In [13]:
matrix1=tf.constant([[39.,34.],
                    [34.,4.],
                    [34.,3.]] ,dtype=tf.float16)
matrix1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[39., 34.],
       [34.,  4.],
       [34.,  3.]], dtype=float16)>

In [14]:
matrix.ndim

2

In [15]:
#creating a tensor
tensor=tf.constant([[[1,34,5],
                   [1,2,4]],
                   [[1,2,4],
                   [2,34,5]],
                   [[234,5,6],
                    [2,4,6]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[  1,  34,   5],
        [  1,   2,   4]],

       [[  1,   2,   4],
        [  2,  34,   5]],

       [[234,   5,   6],
        [  2,   4,   6]]], dtype=int32)>

In [16]:
tensor.ndim

3

# What we created so far
*scalar:is  a single number

*Vector: a number with direction (eg. wind speed and direction)

*Matrix: a 2-dimentional array of numbers
*Tensor: an n- dimentional array of numbers (when  n can be any number, a 0-dimentionaltensor is a scalar, a 1 dimentional tensor is a vector )

# tf.Variable

In [7]:
#create  the same tensor with tf.Variable as above
changeable_tensor =tf.Variable([7,10])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 7, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [8]:
# Lets change one of the element in the cheageable_tensor
changeable_tensor[0]=3
changeable_tensor

# wont work

TypeError: 'ResourceVariable' object does not support item assignment

In [9]:
#try .assign()
changeable_tensor[0].assign(3)
changeable_tensor

# it works 

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 3, 10], dtype=int32)>

In [27]:
#lets try change un changerble
#unchangeable_tensor[0]=4
unchangeable_tensor[0].assign(3)

#can't change it ince its a constant

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Rarely in practice will you ned to decide wherehter to use tf.constant or tf.Varible to create  tensors as TensorFlow does this for yo. However ,if in doubt, ue tf.constant and change later if needed

# Creating random Tensors

Random Tensors are tensors of some abitrary size which contains random numbers

In [33]:
#create two random tensors
random_1=tf.random.Generator.from_seed(42)
random_1=random_1.normal(shape=(3,2))

random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))


#are the equal
random_1,random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

# Shuffle thr Order of elements in a tensor

shuffle a tensor 
 >valuable for when you wants to shuffle your data so that the inherent order doesnt affect learning

In [34]:
not_shuffled = tf.constant([[10,9],
                          [3,4],
                          [2,8]])

not_shuffled.ndim

2

In [35]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 3,  4],
       [ 2,  8]], dtype=int32)>

In [36]:
#shuffle out not_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  8],
       [ 3,  4],
       [10,  9]], dtype=int32)>

In [44]:

tf.random.shuffle(not_shuffled,seed=44)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  8],
       [10,  9],
       [ 3,  4]], dtype=int32)>

In [45]:

tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  9],
       [ 2,  8]], dtype=int32)>

In [47]:
nt_shuff=tf.constant([[2,3,4,24],
                     [4,56,75,4],
                     [23,5,1,6],
                     [12,4,7,9],
                     [34,2,5,7]])
nt_shuff

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[ 2,  3,  4, 24],
       [ 4, 56, 75,  4],
       [23,  5,  1,  6],
       [12,  4,  7,  9],
       [34,  2,  5,  7]], dtype=int32)>

In [49]:
tf.random.shuffle(nt_shuff)

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[23,  5,  1,  6],
       [ 2,  3,  4, 24],
       [34,  2,  5,  7],
       [12,  4,  7,  9],
       [ 4, 56, 75,  4]], dtype=int32)>

 # random Shuffle 
 seed

In [73]:
tf.random.shuffle(nt_shuff,seed=1)

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[34,  2,  5,  7],
       [12,  4,  7,  9],
       [ 2,  3,  4, 24],
       [23,  5,  1,  6],
       [ 4, 56, 75,  4]], dtype=int32)>

In [105]:
tf.random.shuffle(nt_shuff,seed=42) #operation level random seed

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[12,  4,  7,  9],
       [23,  5,  1,  6],
       [34,  2,  5,  7],
       [ 4, 56, 75,  4],
       [ 2,  3,  4, 24]], dtype=int32)>

In [85]:
tf.random.set_seed(42)  #global random seed
tf.random.shuffle(nt_shuff)

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[23,  5,  1,  6],
       [ 2,  3,  4, 24],
       [34,  2,  5,  7],
       [12,  4,  7,  9],
       [ 4, 56, 75,  4]], dtype=int32)>

In [86]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)


In [87]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.7402308], shape=(1,), dtype=float32)
tf.Tensor([0.803156], shape=(1,), dtype=float32)


In [88]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.95831835], shape=(1,), dtype=float32)
tf.Tensor([0.43555546], shape=(1,), dtype=float32)


In [103]:
tf.random.set_seed(42) 
print(tf.random.normal([4]))  # generates 'A1'
print(tf.random.uniform([4])) 

tf.Tensor([ 0.3274685 -0.8426258  0.3194337 -1.4075519], shape=(4,), dtype=float32)
tf.Tensor([0.68789124 0.48447883 0.9309944  0.252187  ], shape=(4,), dtype=float32)


In [111]:
tf.random.set_seed(42)  #global random seed
tf.random.shuffle(nt_shuff,seed=42)

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[12,  4,  7,  9],
       [ 2,  3,  4, 24],
       [ 4, 56, 75,  4],
       [23,  5,  1,  6],
       [34,  2,  5,  7]], dtype=int32)>

In [112]:
tf.random.set_seed(42)  #global random seed
tf.random.shuffle(nt_shuff,seed=42)

<tf.Tensor: shape=(5, 4), dtype=int32, numpy=
array([[12,  4,  7,  9],
       [ 2,  3,  4, 24],
       [ 4, 56, 75,  4],
       [23,  5,  1,  6],
       [34,  2,  5,  7]], dtype=int32)>

# Other Ways to make Tensors
numpy

In [114]:
tf.ones([10,6])

<tf.Tensor: shape=(10, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [116]:
tf.zeros([14,4])

<tf.Tensor: shape=(14, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [117]:
tf.zeros(shape=(4,6))

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

# Turn numpy arrays into tensors
The main difference between a Numpy arrays and Tensorflow tensorsa is that  tensors can run on a GPU computing).

In [4]:
#turn numpy array into tensor
import numpy as np

numpy_A= np.arange(1,25, dtype=np.int16)

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [132]:
A= tf.constant(numpy_A,shape=(2,1,4,3))
A

<tf.Tensor: shape=(2, 1, 4, 3), dtype=int16, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]],


       [[[13, 14, 15],
         [16, 17, 18],
         [19, 20, 21],
         [22, 23, 24]]]], dtype=int16)>

In [136]:
A.ndim

4

<tf.Tensor: shape=(0, 1, 4, 3), dtype=int16, numpy=array([], shape=(0, 1, 4, 3), dtype=int16)>

In [129]:
2*3*4*1

24

# NOTE
in reshaping an array the total number of lelment shold be equal to the product of the shape
>that is an if there are 24 elements the shape can be (2,3,4) or (3,8)

In [168]:
num1=np.arange(0,50)
num1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [170]:
5*5*2

50

In [173]:

#turning num1 into tensor
ten=tf.constant(num1,shape=(5,2,5))
ten

<tf.Tensor: shape=(5, 2, 5), dtype=int64, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])>

In [160]:
ten.ndim

2

# GETTING INFORMATIONS FROM TENSORS

Tensor Attribute
 when dealing witth tensors  you probabily have to be aware of the following
 
1.shape(length(number of elements) of each of the dimensions of a tensor
>tensor.shape

2.Rank: number of tensor dimentions.
>scalar has 0 rank
>>vector has 1 rank
>>>matrix has 2 rank
>>>>tensor has rank n

3.Axis or dimension( Aparticular dimension of a tensor).
>tensor[0],tensor[:,1]...

4.size the total number of items in the tensor
>tf.size(tensor)

In [10]:
rank4_tensor = tf.zeros(shape=(2,3,4,5))
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [11]:
rank4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [12]:
rank4_tensor.shape,rank4_tensor.ndim,tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [40]:
#get various attribute of our tensor
def aboutTensor(rank4_tensor):
    print("Datatype of every element: ",rank4_tensor.dtype)
    print("Number of dimensions (rank):",rank4_tensor.ndim)
    print("Shape of the tensor: ",rank4_tensor.shape)
    print("Elements along the 0 axis: ",rank4_tensor.shape[0])
    print("Elements along the last axis: ",rank4_tensor.shape[-1])
    print("Total elements in the tensor: ",tf.size(rank4_tensor))
    print("Total elements in the tensor: ",tf.size(rank4_tensor).numpy())

# Indexing Tensors
tensors can be indexed just like list

In [17]:
#Get the first 2 element of each dimension
rank4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [18]:
#Get the first element of each dimension from each index except the first one

rank4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [21]:

rank4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [28]:
num=np.arange(1,121)
num

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120])

In [31]:
rank2=tf.constant(num,shape=(2,3,4,5))
rank2

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int64, numpy=
array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])>

In [37]:
rank2[:1,:3,:2,:3]

<tf.Tensor: shape=(1, 3, 2, 3), dtype=int64, numpy=
array([[[[ 1,  2,  3],
         [ 6,  7,  8]],

        [[21, 22, 23],
         [26, 27, 28]],

        [[41, 42, 43],
         [46, 47, 48]]]])>

# Add another dimension to the tensor

In [39]:
rank3=tf.constant([[1,2],
                  [3,4],
                  [5,6]])
rank3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [41]:
aboutTensor(rank3)

Datatype of every element:  <dtype: 'int32'>
Number of dimensions (rank): 2
Shape of the tensor:  (3, 2)
Elements along the 0 axis:  3
Elements along the last axis:  2
Total elements in the tensor:  tf.Tensor(6, shape=(), dtype=int32)
Total elements in the tensor:  6


In [48]:
#last item of each row
rank3[:,-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 4, 6], dtype=int32)>

In [49]:
rank2[:,:,:,-1]

<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
array([[[  5,  10,  15,  20],
        [ 25,  30,  35,  40],
        [ 45,  50,  55,  60]],

       [[ 65,  70,  75,  80],
        [ 85,  90,  95, 100],
        [105, 110, 115, 120]]])>

In [54]:
#add-in extra dimension to our rank 3 tensor
rank4=rank3[...,tf.newaxis]
rank4

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [58]:
rank4


<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [59]:
#alternate to tf.newaxis
tf.expand_dims(rank3,axis=-1)

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]]], dtype=int32)>

In [66]:
tf.expand_dims(rank3,axis=0)

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)>

# Manlpulating  tensor 
>Tensor operating


In [67]:
tens= tf.constant([[10,2],[4,5]])
#unchanged tensor
tens + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 12],
       [14, 15]], dtype=int32)>

In [69]:
#changed
tens=tens+10

In [70]:
tens

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 12],
       [14, 15]], dtype=int32)>

In [72]:
#multiplication 
tens*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 120],
       [140, 150]], dtype=int32)>

In [73]:
#Subtraction
tens-100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-80, -88],
       [-86, -85]], dtype=int32)>

In [74]:

#tensorflow built in functions

In [75]:
tf.multiply(tens,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 120],
       [140, 150]], dtype=int32)>

In [76]:
tf.add(tens,20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 32],
       [34, 35]], dtype=int32)>

In [78]:
tf.subtract(tens,100)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-80, -88],
       [-86, -85]], dtype=int32)>

# Matrix Multiplication
most commom ML operation

>multipling matrix  involves dot product of the row of each matrix by each column of the second 

In [81]:
ten1=tf.constant([[1,2,5],
                 [7,2,1],
                  [3,3,3]])

ten2=tf.constant([[3,5],
                 [6,7],
                  [1,8]])
ten1,ten2

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [82]:
#in tensorflow
tf.matmul(ten1,ten2 )

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [83]:
#multipling matrix 
ten1@ten2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

# Note i
>multiplying matrix 
1. Inner Dimension must match
2.The resulting matrix has the shape of the outer dimension


(a,b)*(b,r)=(b,r)

In [14]:
X=tf.constant([[1,2],
              [3,4],
              [5,6]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [15]:
Y=tf.constant([[7,8],
              [9,10],
              [11,12]])
Y


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [16]:
X.shape,Y.shape
#multiplying wont work till we do something about the shape
X@Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [17]:
#lets change shape of a matrix 
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [18]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [19]:
#At shape is ok to multiply
X@tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [20]:
#same as
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [21]:
#reshaping the X tensor instead
tf.reshape(X,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [22]:
tf.reshape(X,shape=(2,3))@Y


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [23]:
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [30]:
tf.tensordot(tf.reshape(X, shape=(2,3)),Y)

TypeError: Missing required positional argument

In [24]:
#CAN DO SAME WITH "transpose"

In [25]:
 tf.transpose(X),tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [26]:
#TRY matrix multiplication with transpose rather than shape

In [27]:
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

# NOTE II
Matrix multiplication is also refered to as the dot product

You can perform matrix multipliction using:

    *'tf.matmul()'
    *'tf.tensordot()'
    *'@'(numpy)
    
>transposing is fliping the axes

>reshaping is just reshuffling

In [38]:
#reshape
tf.reshape(X,shape=(2,3)),tf.reshape(Y,shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>)

In [39]:
#transposing
tf.transpose(X),tf.transpose (Y)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  9, 11],
        [ 8, 10, 12]], dtype=int32)>)

In [31]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

NameError: name 'he' is not defined

In [40]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [47]:
#Performing matrix multiplication between X and Y (TRANSPOSE)
# tf.tensordot(X,tf.transpose(Y),axes=1)
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [48]:
#perform matrix multiplication between X and Y (RESHAPE)
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [92]:
#To understand the shape of the matrix
print(f"Normal Y:")
print(Y,'\n')
print("Reshaped to (2,3) :")
print(tf.reshape(Y,shape=(2,3)),"\n")
print("Y transposed :")
print(tf.transpose(Y))



Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped to (2,3) :
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed :
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


 # Final NOTE on Multiplication of matrix:
 Genrally when performing matrix multiplication on two tensors and one of the axes does not line up , you will transpose (rather than reshape ) one of the tensors to  satisfy the matrix multiplication rules.

In [95]:
#so here this will be 
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

hey  there


TypeError: unsupported operand type(s) for @: 'list' and 'list'

## Change Dtype of TENSOR
*the 32 in bit is precision and means it takes 32 bit of memory 
int32
float32 
*There are lower precision dtypes,
>float16

>bfloat16

which takes 16 bits of memory instead
modern accelerators can run operations faster in the 16-bit dtype,as they have the specialized hardware to run 16-bit computation and 16-bit dtype can be read from memory faster



NVIDIA GPUs can run operations in float16 faster that float32

TPUs can run operation in bfloat16 faster that float32

In [7]:
B = tf.constant([1,23.,4.,5.,3.])
B.dtype

tf.float32

In [8]:
C = tf.constant([1.2,4.5,6.,65.])
C.dtype

tf.float32

In [9]:
#change the float32 to float16 (reduce precision)
D = tf.cast(B,dtype=tf.float16)
D,D.dtype

(<tf.Tensor: shape=(5,), dtype=float16, numpy=array([ 1., 23.,  4.,  5.,  3.], dtype=float16)>,
 tf.float16)

In [10]:

#change from float32 to int16
E = tf.cast(C,dtype=tf.int16)
E

<tf.Tensor: shape=(4,), dtype=int16, numpy=array([ 1,  4,  6, 65], dtype=int16)>

# Aggregating Tensors
meaning condensing them from multiple values down to a smaller amount of values

In [11]:
#data
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [12]:
#Get the abasolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

# Formas of Aggregation

*mean of tensor

*maximum of a tensor

*minimum of a tensor

*sum of tensor

In [13]:
#Creating random tensor with values btn 0-100 size 50
E=tf.constant(np.random.randint(1,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([62, 74, 23, 53, 18, 36, 61, 12, 77, 22, 12, 61, 15, 71, 78, 47, 13,
       18, 52, 55, 23, 37, 23, 16, 44, 98, 90, 57, 17, 83, 18, 10, 85, 98,
        1, 85, 32, 39,  3, 17, 37, 73, 70, 14, 53, 29, 44, 13, 74, 98])>

In [14]:
tf.size(E),E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [15]:
#Find min of tensor
tf.reduce_min(E)



<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [16]:
#numpy
np.min(E)

1

In [17]:
#find Max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [18]:
np.max(E)

98

In [19]:
#Find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=44>

In [20]:
np.mean(E)

44.82

In [21]:
#Find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2241>

In [22]:
np.sum(E)

2241

# Aggregation ii

# *EXERCISE
* VARIANCE 
* STANDARD DIVIATION

The term variance refers to a statistical measurement of the spread between numbers in a data set. More specifically, variance measures how far each number in the set is from the mean (average)


Standard deviation is a statistic that measures the dispersion of a dataset relative to its mean and is calculated as the square root of the variance. 

In [34]:
#Find the variance of our tensor
#just so you remeber you can find it without importing tfp
import tensorflow_probability as tfp #import if not avilable pip install modulee







tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=809>

In [48]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=809.5>

In [30]:
np.var(E)

809.2275999999999

In [40]:
#find Standard Deviation
tfp.stats.stddev(tf.cast(E,dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=28.45>

In [45]:
tf.math.reduce_std(tf.cast(E,dtype=tf.float16))


<tf.Tensor: shape=(), dtype=float16, numpy=28.45>

In [49]:
np.std(E)

28.44692602022229

# ^^^^Note i (Aggregation) ^^^^^^
* When you receive a typerror try changing the dtype 
^

# Positional Maximum & Minimum

In [50]:
##   Create a new tensor for  finding the min and max

In [57]:
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [58]:
#at whch index does a max number occur
#find positional position
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [54]:
np.argmax(F)

42

In [59]:
#index on our largest value position
#position (index ) of the largest number in the tensor
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [60]:
#Find the max value of F 
#the value at the max position 
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [61]:
#Check for equality in max value
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [62]:
#at Which index does the min value occur
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [63]:
np.argmin(F)

16

In [66]:
#Check for value at min position
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [67]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

# Squeezing a Tensor
Removes dimention of size 1 from the shape of a tensor
* tf.squeeze(t)

In [69]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [73]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [74]:
G_squeezed = tf.squeeze(G)
G_squeezed,G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

# One Hot Encoding
* encoding categorical vales to numerical values

In [81]:
#create a list of indices
some_list = [0,1,2,3] # could be red ,green , blue ,brown

#One hot encoding our list of indices
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [83]:
#Customize one hot encoding values
tf.one_hot(some_list,depth=4,on_value="Yes",off_value='No')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

# Squaring,log,square root

In [84]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [86]:
#Square it
# tf.square
tf.math.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [89]:
#Square root
#method requres a not int dtype
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [91]:
#find LOG
#method requres a not int dtype
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# Tensors and Numpy
* Numpy the fundamental package for scientific computing with python

* #Note: One main difference between a TensorFow tensor and a Numpy array is that a TensorFlow tensor can be runo a GPU or TPU(for faster numeric processing). 

In [93]:
#create a tensor directly from numpy
J=tf.constant(np.array([1.,2.3,4.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1. , 2.3, 4. ])>

In [95]:
#Convert out tensor back to  a Numpy
np.array(J),type(np.array(J))

(array([1. , 2.3, 4. ]), numpy.ndarray)

In [96]:
#or
J.numpy()

array([1. , 2.3, 4. ])

In [98]:
#The default types of each are slightly different
numpy_J=tf.constant(np.array([1.,23.,4.,45.,0.1]))
tensor_J= tf.constant([1.,23.,4.,45.,0.1])

#check the datatypes of eacch
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)

# Finding access to TPUs

In [102]:
tf.config.list_physical_devices()

[]

#changing the proccessor in Colab
*Runtime
*change runtime type
>select type:
* GPU
* TPU

#NOTE: The runtime will reset after slecting a processor


>To check the  type of GPU
* !nvidea-smi 